// Accent color mapping for catalogue templates
export const accentColors: Record<string, { primary: string; gradient: string; gradientHover: string; bg: string; bgLight: string; text: string; border: string; ring: string }> = {
  emerald: {
    primary: "#10b981",
    gradient: "from-emerald-500 to-teal-600",
    gradientHover: "from-emerald-600 to-teal-700",
    bg: "bg-emerald-500",
    bgLight: "bg-emerald-50",
    text: "text-emerald-600",
    border: "border-emerald-200",
    ring: "ring-emerald-500/20",
  },
  blue: {
    primary: "#3b82f6",
    gradient: "from-blue-500 to-indigo-600",
    gradientHover: "from-blue-600 to-indigo-700",
    bg: "bg-blue-500",
    bgLight: "bg-blue-50",
    text: "text-blue-600",
    border: "border-blue-200",
    ring: "ring-blue-500/20",
  },
  rose: {
    primary: "#f43f5e",
    gradient: "from-rose-500 to-pink-600",
    gradientHover: "from-rose-600 to-pink-700",
    bg: "bg-rose-500",
    bgLight: "bg-rose-50",
    text: "text-rose-600",
    border: "border-rose-200",
    ring: "ring-rose-500/20",
  },
  amber: {
    primary: "#f59e0b",
    gradient: "from-amber-500 to-orange-600",
    gradientHover: "from-amber-600 to-orange-700",
    bg: "bg-amber-500",
    bgLight: "bg-amber-50",
    text: "text-amber-600",
    border: "border-amber-200",
    ring: "ring-amber-500/20",
  },
  violet: {
    primary: "#8b5cf6",
    gradient: "from-violet-500 to-purple-600",
    gradientHover: "from-violet-600 to-purple-700",
    bg: "bg-violet-500",
    bgLight: "bg-violet-50",
    text: "text-violet-600",
    border: "border-violet-200",
    ring: "ring-violet-500/20",
  },
  cyan: {
    primary: "#06b6d4",
    gradient: "from-cyan-500 to-sky-600",
    gradientHover: "from-cyan-600 to-sky-700",
    bg: "bg-cyan-500",
    bgLight: "bg-cyan-50",
    text: "text-cyan-600",
    border: "border-cyan-200",
    ring: "ring-cyan-500/20",
  },
  indigo: {
    primary: "#6366f1",
    gradient: "from-indigo-500 to-blue-600",
    gradientHover: "from-indigo-600 to-blue-700",
    bg: "bg-indigo-500",
    bgLight: "bg-indigo-50",
    text: "text-indigo-600",
    border: "border-indigo-200",
    ring: "ring-indigo-500/20",
  },
  orange: {
    primary: "#f97316",
    gradient: "from-orange-500 to-red-600",
    gradientHover: "from-orange-600 to-red-700",
    bg: "bg-orange-500",
    bgLight: "bg-orange-50",
    text: "text-orange-600",
    border: "border-orange-200",
    ring: "ring-orange-500/20",
  },
};

export function getAccent(colorKey: string | null | undefined) {
  return accentColors[colorKey || "emerald"] || accentColors.emerald;
}
