// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kslvhesqtmubjqumwjzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtzbHZoZXNxdG11YmpxdW13anp1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM2MTc3NzIsImV4cCI6MjA3OTE5Mzc3Mn0.hc-ZsoGOpVPtxQ4uqPC8We3Hu_mRqfZEXdIHY6oYxQ0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});